/* Generated by Together */

package com.joviansoft.framework.query;

import java.io.Serializable;

/**
 * 数据库中的字段元数据定义类
 * <p>Title: 通用报表设计系统</p>
 * <p>Description: GReport Designer System</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: GNT</p>
 * @author kgb_hz@126.com,kgb@primetech.com.cn
 * @version 1.0
 */
public class FieldDef
    implements Serializable {
  private String fieldName; //字段名称
  private String displayName; //显示名称
  private int fieldType; //字段类型
  private String fieldTypeName;//字段类型名字 //hl add 20100201
  private int fieldWidth; //字段长度
  private boolean isVisible = true; //是否显示

  
  public String getFieldTypeName() {
	return fieldTypeName;
}

public void setFieldTypeName(String fieldTypeName) {
	this.fieldTypeName = fieldTypeName;
}

public String getFieldName() {
    return fieldName;
  }

  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }

  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public int getFieldType() {
    return fieldType;
  }

  public void setFieldType(int fieldType) {
    this.fieldType = fieldType;
  }

  public int getFieldWidth() {
    return fieldWidth;
  }

  public void setFieldWidth(int fieldWidth) {
    this.fieldWidth = fieldWidth;
  }

  public boolean isIsVisible() {
    return isVisible;
  }

  public void setIsVisible(boolean isVisible) {
    this.isVisible = isVisible;
  }
}
