/* Generated by Together */

package com.joviansoft.framework.query;

import java.util.*;

/**
 *
 * <p>Title: Prodb</p>
 * <p>Description: 常住人口管理信息系统（二代证）省级库</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: GNT(ZJHZ)</p>
 * @author kgb_hz@126.com,kgb@primetech.com.cn
 * @version 1.0
 */
public interface IResultSetListMap
    extends List {
  /**
   *
   * @param mapOneRecord
   */
  void addOneRow(Map mapOneRecord);

  /**
   *
   * @param iIndex
   * @return
   */
  Map getOneRow(int iIndex);

  /**
   *
   * @return
   */
  MetaData getMetaData();

  /**
   *
   * @param pMetaData
   */
  void setMetaData(MetaData pMetaData);




}
