/* Generated by Together */

package com.joviansoft.framework.query;

import java.io.Serializable;
import java.util.*;

/**
 * 数据库表中的元数据定义
 * <p>Title: 通用报表设计系统</p>
 * <p>Description: GReport Designer System</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: GNT</p>
 * @author kgb_hz@126.com,kgb@primetech.com.cn
 * @version 1.0
 */
public class MetaData
    extends TreeMap
    implements Serializable, Map {

  public FieldDef getFieldDef(String strFieldName) {
    return (FieldDef) get(strFieldName);
  }

  /**
   *
   * @param aFieldDef
   */
  public void addFieldDef(FieldDef aFieldDef) {
    put(aFieldDef.getFieldName(), aFieldDef);
  }

  /**
   *
   * @return
   */
  public FieldDef[] getFieldDefs() {
    FieldDef[] arryFieldDefs = null;
    if (!isEmpty()) {
      arryFieldDefs = new FieldDef[size()];
      int i = 0;
      for (Iterator iter = entrySet().iterator(); iter.hasNext(); ) {
        Map.Entry aEntry = (Map.Entry) iter.next();
        arryFieldDefs[i] = (FieldDef) aEntry.getValue();
        i++;
      }
    }
    return arryFieldDefs;
  }

  /**
   *
   * @param fieldDefs
   */
  public void addFieldDefs(FieldDef[] fieldDefs) {
    if (fieldDefs != null) {
      for (int i = 0; i < fieldDefs.length; i++) {
        FieldDef aFieldDef = fieldDefs[i];
        put(aFieldDef.getFieldName(), aFieldDef);
      }
    }
  }

  /**
   *
   * @param mapFieldDefs
   */
  public void addFieldDefs(Map mapFieldDefs) {
    putAll(mapFieldDefs);
  }

  /**
   *
   * @param lstFieldDefs
   */
  public void addFieldDefs(List lstFieldDefs) {
    if (lstFieldDefs != null) {
      //转换为字段定义数组
      FieldDef[] arryFieldDefs = (FieldDef[]) lstFieldDefs.toArray(new FieldDef[
          lstFieldDefs.size()]);
      //添加字段定义数组
      addFieldDefs(arryFieldDefs);
    }
  }

  /**
   *
   * @return
   */
  public int getFieldCount() {
    return size();
  }

}
