/* Generated by Together */

package com.joviansoft.framework.query;

import java.util.*;

/**
 *
 * <p>Title: Prodb</p>
 * <p>Description: 常住人口管理信息系统（二代证）省级库</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: GNT(ZJHZ)</p>
 * @author kgb_hz@126.com,kgb@primetech.com.cn
 * @version 1.0
 */
public class ResultSetListMap
    extends ArrayList
    implements IResultSetListMap {

  //结果集元数据定义
  private MetaData _metadata = null;


  public MetaData getMetaData() {
    return this._metadata;
  }

  public void setMetaData(MetaData pMetaData) {
    this._metadata = pMetaData;
  }

  /**
   *
   * @param mapOneRecord
   */
  public void addOneRow(Map mapOneRecord) {
    this.add(mapOneRecord);
  }

  /**
   *
   * @param iIndex
   * @return
   */
  public Map getOneRow(int iIndex) {
    return (Map)this.get(iIndex);
  }


}
